#include "City.hpp"

using namespace pandemic;

std::string pandemic::city_to_string(pandemic::City c) {
    switch (c) {
        case pandemic::City::Algiers :
            return "Algiers";
        case pandemic::City::Atlanta:
            return "Atlanta";
        case pandemic::City::Baghdad:
            return "Baghdad";
        case pandemic::City::Bangkok:
            return "Bangkok";
        case pandemic::City::Beijing:
            return "Beijing";
        case pandemic::City::Bogota:
            return "Bogota";
        case pandemic::City::BuenosAires:
            return "BuenosAires";
        case pandemic::City::Cairo:
            return "Cairo";
        case pandemic::City::Chennai:
            return "Chennai";
        case pandemic::City::Chicago:
            return "Chicago";
        case pandemic::City::Delhi:
            return "Delhi";
        case pandemic::City::Essen:
            return "Essen";
        case pandemic::City::HoChiMinhCity:
            return "HoChiMinhCity";
        case pandemic::City::HongKong:
            return "HongKong";
        case pandemic::City::Istanbul:
            return "Istanbul";
        case pandemic::City::Jakarta:
            return "Jakarta";
        case pandemic::City::Johannesburg:
            return "Johannesburg";
        case pandemic::City::Karachi:
            return "Karachi";
        case pandemic::City::Khartoum:
            return "Khartoum";
        case pandemic::City::Kinshasa:
            return "Kinshasa";
        case pandemic::City::Kolkata:
            return "Kolkata";
        case pandemic::City::Lagos:
            return "Lagos";
        case pandemic::City::Lima:
            return "Lima";
        case pandemic::City::London:
            return "London";
        case pandemic::City::LosAngeles:
            return "LosAngeles";
        case pandemic::City::Madrid:
            return "Madrid";
        case pandemic::City::Manila:
            return "Manila";
        case pandemic::City::MexicoCity:
            return "MexicoCity";
        case pandemic::City::Miami:
            return "Miami";
        case pandemic::City::Milan:
            return "Milan";
        case pandemic::City::Montreal:
            return "Montreal";
        case pandemic::City::Moscow:
            return "Moscow";
        case pandemic::City::Mumbai:
            return "Mumbai";
        case pandemic::City::NewYork:
            return "NewYork";
        case pandemic::City::Osaka:
            return "Osaka";
        case pandemic::City::Paris:
            return "Paris";
        case pandemic::City::Riyadh:
            return "Riyadh";
        case pandemic::City::SanFrancisco:
            return "SanFrancisco";
        case pandemic::City::Santiago:
            return "Santiago";
        case pandemic::City::SaoPaulo:
            return "SaoPaulo";
        case pandemic::City::Seoul:
            return "Seoul";
        case pandemic::City::Shanghai:
            return "Shanghai";
        case pandemic::City::StPetersburg:
            return "StPetersburg";
        case pandemic::City::Sydney:
            return "Sydney";
        case pandemic::City::Taipei:
            return "Taipei";
        case pandemic::City::Tehran:
            return "Tehran";
        case pandemic::City::Tokyo:
            return "Tokyo";
        case pandemic::City::Washington:
            return "Washington";
    }
    return "";
}